CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(20) NOT NULL ,
    uri VARCHAR(20) NOT NULL ,
    ip VARCHAR(20) NOT NULL ,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);